name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew clean build

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish docker images
        timeout-minutes: 5
        run: |
          docker build -t docker.io/peepoclown/rsoi-lab4:cars-latest ./cars-service
          docker build -t docker.io/peepoclown/rsoi-lab4:payment-latest ./payment-service
          docker build -t docker.io/peepoclown/rsoi-lab4:rental-latest ./rental-service
          docker build -t docker.io/peepoclown/rsoi-lab4:gateway-latest ./gateway-service
          docker push docker.io/peepoclown/rsoi-lab4:cars-latest
          docker push docker.io/peepoclown/rsoi-lab4:payment-latest
          docker push docker.io/peepoclown/rsoi-lab4:rental-latest
          docker push docker.io/peepoclown/rsoi-lab4:gateway-latest

      - name: Deploy to kubernetes
        timeout-minutes: 5
        run: |
          kubectl config set-cluster rsoi-cluster --server="${{ secrets.K8S_SERVER }}"
          kubectl config set-credentials dev --token="${{ secrets.K8S_KUBECONFIG }}"
          kubectl config set clusters.rsoi-cluster.certificate-authority-data "${{ secrets.K8S_CLUSTER_CERT }}"
          kubectl config set-context production --cluster=rsoi-cluster --user=dev --namespace=peepoclown
          kubectl config use-context production
          helm upgrade --install rsoi-lab4 ./k8s/car-rental-system-chart
          kubectl apply -f k8s/ingress.yml

      - name: Wait pods up
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/collection.json
          environment: postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"